name: google_drive_proj
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  percent_indicator: ^2.1.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
   - assets/images/googledrive_app_img.png
   - assets/images/pdf
   - assets/images/dropbox.ico
   - assets/images/google-drive.png
   - assets/images/female_above40.jpg
   - assets/images/Dropbox.png
   - assets/images/diamond_img.jpeg
   - assets/images/artboard___2_3x.png
   - assets/images/shot_x1__1_.png
   - assets/images/Diampnd.jpeg
   - assets/images/image_file.jpg
   - assets/images/dropbox.jpg
   - assets/images/WeeklyUIChalange.png
   - assets/images/xls.png
   - assets/images/mobile_app_hero.png
   - assets/images/mobile_image.jpg
   - assets/images/drp_bx.png
   - assets/images/circle-cropped.png
   - assets/images/doc_crop.jpg
   - assets/images/gallery_img_crop.png
   - assets/images/dots_circle-cropped.png
   - assets/images/circle-cropped_progressbar.png
   - assets/images/white_threedot_crop.png
   - assets/images/white_threedot.png
   - assets/images/pngtree-round-progress-bar-image_1273541.jpg
   - assets/images/circle-cropped_progress.png
   - assets/images/logo.png
   - assets/images/powered_by.png

